//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillDetail
    {
        public long BillDetailID { get; set; }
        public long BillID { get; set; }
        public int ProductID { get; set; }
        public short Quantity { get; set; }
        public decimal Price { get; set; }
    
        public virtual tblBill tblBill { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
