//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComBo
    {
        public tblComBo()
        {
            this.tblBillDetails = new HashSet<tblBillDetail>();
            this.tblProducts = new HashSet<tblProduct>();
        }
    
        public int ComboID { get; set; }
        public string ComboName { get; set; }
        public string ShortcutKey { get; set; }
        public string Avatar { get; set; }
        public bool isDelete { get; set; }
        public bool isHidden { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<tblBillDetail> tblBillDetails { get; set; }
        public virtual ICollection<tblProduct> tblProducts { get; set; }
    }
}
