//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeType
    {
        public tblEmployeeType()
        {
            this.tblEmployeeType_tblEmployee = new HashSet<tblEmployeeType_tblEmployee>();
        }
    
        public int EmployeeTypeID { get; set; }
        public string EmployeeTypeName { get; set; }
        public string Description { get; set; }
        public bool isDelete { get; set; }
        public bool isHidden { get; set; }
    
        public virtual ICollection<tblEmployeeType_tblEmployee> tblEmployeeType_tblEmployee { get; set; }
    }
}
