//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFixedCost
    {
        public tblFixedCost()
        {
            this.tblStatements = new HashSet<tblStatement>();
        }
    
        public int FixedCostID { get; set; }
        public string FixedCostName { get; set; }
        public string Description { get; set; }
        public decimal Money { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool isDelete { get; set; }
        public bool isHiddent { get; set; }
    
        public virtual ICollection<tblStatement> tblStatements { get; set; }
    }
}
