//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier_Material
    {
        public long ObjectID { get; set; }
        public long MaterialID { get; set; }
        public short StoreID { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual tblMaterial tblMaterial { get; set; }
        public virtual tblStore tblStore { get; set; }
        public virtual tblSupplier tblSupplier { get; set; }
    }
}
