//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComboPrice
    {
        public int ComboID { get; set; }
        public decimal Price { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual tblComBo tblComBo { get; set; }
    }
}
