//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDistrict
    {
        public tblDistrict()
        {
            this.tblWards = new HashSet<tblWard>();
        }
    
        public int DistrictID { get; set; }
        public string DistrictName { get; set; }
        public int CityID { get; set; }
        public bool isHidden { get; set; }
        public bool isDelete { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual ICollection<tblWard> tblWards { get; set; }
    }
}
