//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaterial
    {
        public tblMaterial()
        {
            this.Product_Material = new HashSet<Product_Material>();
            this.Supplier_Material = new HashSet<Supplier_Material>();
        }
    
        public long MaterialID { get; set; }
        public string MaterialName { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public string Avatar { get; set; }
        public bool isHidden { get; set; }
        public bool isDelete { get; set; }
    
        public virtual ICollection<Product_Material> Product_Material { get; set; }
        public virtual ICollection<Supplier_Material> Supplier_Material { get; set; }
    }
}
