//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplier
    {
        public tblSupplier()
        {
            this.Supplier_Material = new HashSet<Supplier_Material>();
        }
    
        public long ObjectID { get; set; }
        public short GroupSupplier { get; set; }
    
        public virtual ICollection<Supplier_Material> Supplier_Material { get; set; }
        public virtual tblGroupSupplier tblGroupSupplier { get; set; }
    }
}
