//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampainDetail
    {
        public long CampainDetailID { get; set; }
        public long CampainID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> isPercent { get; set; }
    
        public virtual tblCampaign tblCampaign { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
