//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Attendance
    {
        public int EAId { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ImageUrl { get; set; }
        public string Note { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
