//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public tblAccount()
        {
            this.tblAccount_tblRoles = new HashSet<tblAccount_tblRoles>();
            this.tblAccountGroups = new HashSet<tblAccountGroup>();
            this.tblBills = new HashSet<tblBill>();
        }
    
        public long ObjectID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool isEnable { get; set; }
        public System.DateTime LastLogin { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool isSystem { get; set; }
        public bool isDelete { get; set; }
        public bool isHidden { get; set; }
    
        public virtual ICollection<tblAccount_tblRoles> tblAccount_tblRoles { get; set; }
        public virtual tblObject tblObject { get; set; }
        public virtual ICollection<tblAccountGroup> tblAccountGroups { get; set; }
        public virtual ICollection<tblBill> tblBills { get; set; }
    }
}
