//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticle
    {
        public tblArticle()
        {
            this.tblArticleCat_Article = new HashSet<tblArticleCat_Article>();
        }
    
        public long ArticleID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public bool isHidden { get; set; }
        public bool isDelete { get; set; }
    
        public virtual ICollection<tblArticleCat_Article> tblArticleCat_Article { get; set; }
    }
}
