//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticleCat
    {
        public tblArticleCat()
        {
            this.tblArticleCat_Article = new HashSet<tblArticleCat_Article>();
            this.tblMenus = new HashSet<tblMenu>();
        }
    
        public int ArticleCatID { get; set; }
        public string ArticleCatName { get; set; }
        public Nullable<byte> TreeLevel { get; set; }
        public string TreePatch { get; set; }
        public bool HasChildren { get; set; }
        public Nullable<int> ParentID { get; set; }
        public bool isHidden { get; set; }
        public bool isDelete { get; set; }
    
        public virtual ICollection<tblArticleCat_Article> tblArticleCat_Article { get; set; }
        public virtual ICollection<tblMenu> tblMenus { get; set; }
    }
}
