//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount_tblRoles
    {
        public short RoleID { get; set; }
        public long ObjectID { get; set; }
        public bool Allow { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblRole tblRole { get; set; }
    }
}
