//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCity
    {
        public tblCity()
        {
            this.tblDistricts = new HashSet<tblDistrict>();
        }
    
        public int CityID { get; set; }
        public string CityName { get; set; }
        public bool isHidden { get; set; }
        public bool isDelete { get; set; }
    
        public virtual ICollection<tblDistrict> tblDistricts { get; set; }
    }
}
