//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMedia
    {
        public tblMedia()
        {
            this.tblMediaCat_tblMedia = new HashSet<tblMediaCat_tblMedia>();
        }
    
        public int MediaID { get; set; }
        public string MediaName { get; set; }
        public string Alt { get; set; }
        public bool isDelete { get; set; }
        public bool isHidden { get; set; }
    
        public virtual ICollection<tblMediaCat_tblMedia> tblMediaCat_tblMedia { get; set; }
    }
}
