//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        public tblMenu()
        {
            this.tblArticleCats = new HashSet<tblArticleCat>();
        }
    
        public short MenuID { get; set; }
        public string MenuName { get; set; }
        public Nullable<byte> TreeLevel { get; set; }
        public string TreePatch { get; set; }
        public bool HasChildren { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual ICollection<tblArticleCat> tblArticleCats { get; set; }
    }
}
