//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblObject
    {
        public long ObjectID { get; set; }
        public string ObjectName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> WardID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Email { get; set; }
        public string Email1 { get; set; }
        public string Phone { get; set; }
        public string Phone1 { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<long> UpdateBy { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<bool> isHiddent { get; set; }
        public Nullable<bool> isCustomer { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
