//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRole
    {
        public tblRole()
        {
            this.tblAccount_tblRoles = new HashSet<tblAccount_tblRoles>();
            this.tblAccountGroups = new HashSet<tblAccountGroup>();
        }
    
        public short RoleID { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public short TableID { get; set; }
    
        public virtual ICollection<tblAccount_tblRoles> tblAccount_tblRoles { get; set; }
        public virtual tblTable tblTable { get; set; }
        public virtual ICollection<tblAccountGroup> tblAccountGroups { get; set; }
    }
}
