//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStatement
    {
        public long StatementID { get; set; }
        public string Title { get; set; }
        public bool StatementType { get; set; }
        public decimal Money { get; set; }
        public string Description { get; set; }
        public string ReceiverName { get; set; }
        public Nullable<long> ReceiverID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long CreateBy { get; set; }
        public bool isFixedCost { get; set; }
        public Nullable<int> FixedCostID { get; set; }
        public bool isDelete { get; set; }
        public bool isHidden { get; set; }
    
        public virtual tblFixedCost tblFixedCost { get; set; }
    }
}
