//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTable
    {
        public tblTable()
        {
            this.tblRoles = new HashSet<tblRole>();
        }
    
        public short TableID { get; set; }
        public string TableName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tblRole> tblRoles { get; set; }
    }
}
