//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Material
    {
        public long MaterialID { get; set; }
        public short StoreID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public decimal MaterialQuantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MaterialQuantityAlert { get; set; }
        public string Note { get; set; }
        public int SMId { get; set; }
    
        public virtual tblMaterial tblMaterial { get; set; }
        public virtual tblStore tblStore { get; set; }
    }
}
