//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticleCat_Article
    {
        public int ArticleCatID { get; set; }
        public long ArticleID { get; set; }
        public Nullable<byte> IndexASC { get; set; }
    
        public virtual tblArticle tblArticle { get; set; }
        public virtual tblArticleCat tblArticleCat { get; set; }
    }
}
