//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillDetail
    {
        public long BillDetailID { get; set; }
        public long BillID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<short> ProductQuantity { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<int> ComboID { get; set; }
        public Nullable<short> ComboQUantity { get; set; }
        public Nullable<decimal> ComboPrice { get; set; }
        public Nullable<int> ProductCompain { get; set; }
        public Nullable<int> ComboCompain { get; set; }
        public string Note { get; set; }
    
        public virtual tblBill tblBill { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblComBo tblComBo { get; set; }
    }
}
