//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFixedAsset_Store_Shop
    {
        public int FixedAssetID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> ShopID { get; set; }
        public short StoreID { get; set; }
    
        public virtual tblFixedAsset tblFixedAsset { get; set; }
        public virtual tblShop tblShop { get; set; }
        public virtual tblStore tblStore { get; set; }
    }
}
