//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BANHSAURIENG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWard
    {
        public int WardID { get; set; }
        public string WardName { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public bool isHidden { get; set; }
        public bool isDelete { get; set; }
    
        public virtual tblDistrict tblDistrict { get; set; }
    }
}
